version: '3.8'

services:
  app:
    build: .
    container_name: tonkitlab-app-localstack
    ports:
      - "5000:5000"
    env_file:
      - .env.localstack
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - tonkitlab-network
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./app.py:/app/app.py
      - ./credentials.py:/app/credentials.py
      - ./credentials_envi.py:/app/credentials_envi.py
    restart: unless-stopped

  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=cognito-idp,dynamodb,s3,secretsmanager
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SKIP_SSL_CERT_DOWNLOAD=1
      - PERSISTENCE=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts:/docker-entrypoint-initaws.d"
      - "localstack-data:/var/lib/localstack"
    networks:
      - tonkitlab-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  tonkitlab-network:
    driver: bridge

volumes:
  localstack-data:
